### ISSUE TITLE
CSV_GEN as separate project

### ISSUE THREAD

**Issue by cstewart87** [SteveMcGrath/pySecurityCenter#11]
First off, great tool!  Best security center API client I've come across.

Have you considered making csv_gen its own module/project?  It would be nice to be able to clone just the csv_gen and use that as a 'front-end' to pySecurityCenter

**Comment by SteveMcGrath** [comment]
Honestly, I never thought of doing so.  the CSV gen script is mostly designed to be a stop-gap until SC5.  Further the example, while fairly complex, is simply an example and I encourage people to use it as an example for their own project.
