### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by ewunder** [SteveMcGrath/pySecurityCenter#12]
https://github.com/SteveMcGrath/pySecurityCenter/blob/master/SecurityCenter5_REST_API.md

**Comment by SteveMcGrath** [comment]
I'm aware, I haven't had the chance to write it yet.

**Comment by SteveMcGrath** [comment]
initial document committed into git.

**Comment by ewunder** [comment]
Cool, thank you!

**Comment by SteveMcGrath** [comment]
I would also say take a look at the examples in the sc5 folder.  they are what I have written so far using the new module.

**Comment by ewunder** [comment]
Will do, your efforts are much appreciated and helpful!!
