### ISSUE TITLE
ImportError: No module named 'sc4' while importing SecurityCenter 5 in python 3.5

### ISSUE THREAD

**Issue by jarda-wien** [SteveMcGrath/pySecurityCenter#18]
Hi,
I was just trying to to use the new SC5 API and are failing on the first step:
<code>
from securitycenter import SecurityCenter5

xxxx\site-packages\securitycenter\__init__.py", line 1, in <module>
from sc4 import SecurityCenter4 as SecurityCenter
ImportError: No module named 'sc4'
</code>

I am running version 2.1.11 installed via pip and python 3.5.

This seems to be related to http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html and can be fixed easily in securitycenter\__init__.py by using a dot in front of sc4, sc5 and nessus in the imports.

On the other hand, this leads to many more issues because of python 3.5 not having urrlib2 (merged to urllib) and StringIO. It is probably possible to comment out the sc4 imports in __init__.py and not use this code at all.

**Comment by SteveMcGrath** [comment]
it is actually.  My goal is to release a new version soon that is more SC5 and forward focused and eventually drop the old SC4 code.  I'm thinking of doing it as a major rev just to make sure people can keep track.

**Comment by SteveMcGrath** [comment]
please look at the new 3.x branch
