### ISSUE TITLE
How can Scandownloader handle LARGE scan results?

### ISSUE THREAD

**Issue by gitclancy** [SteveMcGrath/pySecurityCenter#19]
How can the script be modified to pipe the scan result directly to a zip file on disk without staging in memory.  We have scan result files exceeding 1 GB zipped and the script blows memory even with 16GB RAM.

**Comment by SteveMcGrath** [comment]
Are you referring to?:

https://github.com/SteveMcGrath/pySecurityCenter/blob/master/examples/sc5/download_scans/downloader.py

**Comment by gitclancy** [comment]
Hi Steve,

That be it.  I stole your code and am using it to automatically download weekly scan files.  It works for all but the largest scan files.  Now that we doing credentialed scans, the files are getting larger.
Any recommendations on how to get the zip file down directly without staging in memory?

Regards,
Earl



[cid:494BDDB9-0FAC-4257-9F42-420C5F51D58C]
Earl Bye
ebye@mmm.com<mailto:ebye@mmm.com>
3M Center, 224-4E-21, 4I3
St. Paul, MN, USA
Infrastructure Vulnerability Specialist
3M Information Security, Risk & Compliance
Tel:  651-737-4427 (Triminet: 737-4427)
Fax:  651-733-3979 (Triminet: 733-3979)

The information contained in this message and any attachments is intended only for the use of the individual or entity to which it is addressed, and may contain information that is PRIVILEGED, CONFIDENTIAL, and exempt from disclosure under applicable law. If you have received this message in error, you are prohibited from copying, distributing, or using the information. Please contact the sender immediately by return e-mail and delete the original message from your system.

**Comment by SteveMcGrath** [comment]
I'd recommend replacing the existing post and write code with something closer to this:

http://stackoverflow.com/questions/14114729/save-a-large-file-using-the-python-requests-library?answertab=votes#tab-top

**Comment by gitclancy** [comment]
Thanks, Steve.  I will try!

Regards,
Earl

[cid:7536F787-DB13-4518-AF2F-479F9E704432]
Earl Bye
ebye@mmm.com<mailto:ebye@mmm.com>
3M Center, 224-4E-21, 4I3
St. Paul, MN, USA
Infrastructure Vulnerability Specialist
3M Information Security, Risk & Compliance
Tel:  651-737-4427 (Triminet: 737-4427)
Fax:  651-733-3979 (Triminet: 733-3979)

The information contained in this message and any attachments is intended only for the use of the individual or entity to which it is addressed, and may contain information that is PRIVILEGED, CONFIDENTIAL, and exempt from disclosure under applicable law. If you have received this message in error, you are prohibited from copying, distributing, or using the information. Please contact the sender immediately by return e-mail and delete the original message from your system.

**Comment by gitclancy** [comment]
Thanks, Steve.  It looks like I cannot use the pySecurityCenter interface to stream the response to a file and instead interface directly using the Python requests library. Is this a correct assumption?

Regards,
Earl

[cid:576FF656-AB13-4D65-B34B-65ADFE00E5FE]
Earl Bye
ebye@mmm.com<mailto:ebye@mmm.com>
3M Center, 224-4E-21, 4I3
St. Paul, MN, USA
Infrastructure Vulnerability Specialist
3M Information Security, Risk & Compliance
Tel:  651-737-4427 (Triminet: 737-4427)
Fax:  651-733-3979 (Triminet: 733-3979)

The information contained in this message and any attachments is intended only for the use of the individual or entity to which it is addressed, and may contain information that is PRIVILEGED, CONFIDENTIAL, and exempt from disclosure under applicable law. If you have received this message in error, you are prohibited from copying, distributing, or using the information. Please contact the sender immediately by return e-mail and delete the original message from your system.
