### ISSUE TITLE
Issue with Specifying Rules

### ISSUE THREAD

**Issue by XjCrazy09** [SteveMcGrath/pySecurityCenter#20]
I realize that this is more than likely an issue with how I am formatting and using your tool more so than a bug with your code.  However, i am having an issue and I thought you might be able to help me if you have the time.  

I currently have a CSV document of about 400 DNS names and IPs.  I was following your example under SC5 "asset_list_batch.py".  This works great if you want to add all of the assets directly into the asset list, but I was hoping to add them to a group.  I have tried editing the json data and tagging it with a group name, but over all doesn't work.  I then tried to add the type dynamic which allows for group tagging, but I keep getting "Please specify rules for this dynamic asset".  Not sure where I am going wrong.  If you could offer any assistance or point me to a resource that I can read I would be greatly appreciative.

**Comment by SteveMcGrath** [comment]
Are you trying to "group" asset lists together?

**Comment by SteveMcGrath** [comment]
@XjCrazy09 any information here?  I will close this issue at the end of the week if I dont hear back from ya
