### ISSUE TITLE
Need both pySecurityCenter 2.1.4 and SecurityCenter 1.0.5 on the same machine

### ISSUE THREAD

**Issue by DanEhrlich** [SteveMcGrath/pySecurityCenter#21]
I am trying to migrate some code from using SecurityCenter 1.0.5 to  pySecurityCenter 2.1.4.  Unfortunately both install themselves as securitycenter.

It would really be a good thing if I could get pySecurityCenter to install someplace else but my setup.py knowledge is limited to running the script.

Any pointers to the appropriate documentation or suggestion on how to proceed will be appreciated.

**Comment by DanEhrlich** [comment]
Well, I figured out a way to do it.  But it was a hack.

**Comment by SteveMcGrath** [comment]
Sorry I didnt get to this sooner, however the SecurityCenter4 class in 2.x is nearly identical to the 1.x SecurityCenter class.
