### ISSUE TITLE
Security Center ImportError: No module named 'httplib'

### ISSUE THREAD

**Issue by pythoncode17** [SteveMcGrath/pySecurityCenter#24]
Objective: 
Log in to Tenable Security Center 5.3.2
Using Python 3.4
Start a Nessus Scan

Python Script:
#from securitycenter import SecurityCenter5
#import securitycenter
#from securitycenter import Client
#sc = SecurityCenter5('https://777.777.7.77:8834')
#sc.login('goat','start^&*+fGh--!end')
#response = sc.get('status')
#print('response=%s'%(response))
from securitycenter import SecurityCenter
sc = securitycenter.SecurityCenter('https://777.777.7.77:8834','goat','start^&*+fGh--!end')
print('Finish')

Run python script
  File "E:\tenable\sc.py", line 8, in <module>
    from securitycenter import SecurityCenter
  File "C:\Python34\lib\site-packages\securitycenter\__init__.py", line 1, in <module>
    from .sc4 import SecurityCenter4 as SecurityCenter
  File "C:\Python34\lib\site-packages\securitycenter\sc4.py", line 6, in <module>
    import os, sys, ssl, random, httplib, logging, mimetypes, urllib2, calendar
**ImportError: No module named 'httplib'**

What do I need to correct in this script?

And do I need to add mod: **from nessrest import ness6rest** to start a Nessus Scan after I log into Security Center?

Thank You

**Comment by paragbaxi** [comment]
There is no httplib in Python3. It's http.client. https://docs.python.org/3.4/library/http.client.html
