### ISSUE TITLE
Problem with ImportError: No module named 'httplib' from securitycenter import SecurityCenter5

### ISSUE THREAD

**Issue by pythoncode17** [SteveMcGrath/pySecurityCenter#25]
To: Paragbaxi

Thank you for taking the time and giving me a reply.

I’m still new to python and I’m having a problem figuring out how to solve this problem.

So I will take a guess.

Error message below:
<b>File "C:\Python34\lib\site-packages\securitycenter\__init__.py", line 1, in <module></b>
<b>File "C:\Python34\lib\site-packages\securitycenter\sc4.py", line 6, in <module></b>
ImportError: No module named 'httplib'

So, I went to GitHub: pySecurityCenter / securitycenter / sc4.py

On line 6 I found: 
<b>import os, sys, ssl, random, httplib, logging, mimetypes, urllib2, calendar</b>

Does this mean I have to remove httplib from the mod?

Do I copy and paste all of: <b>sc4.py</b> into my program below?
Then copy all of: <b> _init_.py</b>?

++++++++++++Program Below+++++++++++++++++++++++
from securitycenter import SecurityCenter5
#import securitycenter
#from securitycenter import Client
#sc = SecurityCenter5('https://128.102.2.36:8834')
#sc.login('swtest','P@ssw0rd!')
#response = sc.get('status')
#print('response=%s'%(response))
import http.client
#from securitycenter import SecurityCenter
#from .nessus import Nessus
sc = securitycenter.SecurityCenter('https://128.102.2.36:8834','swtest','P@ssw0rd!')
#sc = securitycenter.SecurityCenter('https.client.HTTPConnection://128.102.2.36:8834','swtest','P@ssw0rd!')
print('Finish')
++++++++++++Program End+++++++++++++++++++++++
Objected: Login to Tenable Security Center and run a Nessus Scan

Running: Python 3.4 and Security Center 5.3.2

I’m not sure what to do to solve this problem.

Thanks for your help
Pythoncode17

**Comment by paragbaxi** [comment]
https://github.com/SteveMcGrath/pySecurityCenter/pull/27

On Tue, Jun 28, 2016 at 4:20 PM pythoncode17 <notifications@github.com>
wrote:

> To: Paragbaxi
>
> Thank you for taking the time and giving me a reply.
>
> I’m still new to python and I’m having a problem figuring out how to solve
> this problem.
>
> So I will take a guess.
>
> Error message below:
> *File "C:\Python34\lib\site-packages\securitycenter__init__.py", line 1,
> in *
> *File "C:\Python34\lib\site-packages\securitycenter\sc4.py", line 6, in *
> ImportError: No module named 'httplib'
>
> So, I went to GitHub: pySecurityCenter / securitycenter / sc4.py
>
> On line 6 I found:
> *import os, sys, ssl, random, httplib, logging, mimetypes, urllib2,
> calendar*
>
> Does this mean I have to remove httplib from the mod?
>
> Do I copy and paste all of: *sc4.py* into my program below?
> Then copy all of: * init.py*?
>
> ++++++++++++Program Below+++++++++++++++++++++++
> from securitycenter import SecurityCenter5
> #import securitycenter
> #from securitycenter import Client
> #sc = SecurityCenter5('https://128.102.2.36:8834')
> #sc.login('swtest','P@ssw0rd!')
> #response = sc.get('status')
> #print('response=%s'%(response))
> import http.client
> #from securitycenter import SecurityCenter
> #from .nessus import Nessus
> sc = securitycenter.SecurityCenter('
> https://128.102.2.36:8834','swtest','P@ssw0rd!')
> #sc = securitycenter.SecurityCenter('https.client.HTTPConnection://
> 128.102.2.36:8834','swtest','P@ssw0rd!')
> print('Finish')
> ++++++++++++Program End+++++++++++++++++++++++
> Objected: Login to Tenable Security Center and run a Nessus Scan
>
> Running: Python 3.4 and Security Center 5.3.2
>
> I’m not sure what to do to solve this problem.
>
> Thanks for your help
> Pythoncode17
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SteveMcGrath/pySecurityCenter/issues/25>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AA6R8cez8S6jfOOI7AuOwdQQE1jQgRY5ks5qQYIGgaJpZM4JAfqv>
> .
>
-- 
Parag
