### ISSUE TITLE
Getting AttributError and ImportError while running code

### ISSUE THREAD

**Issue by sidgupt** [SteveMcGrath/pySecurityCenter#37]
Hey Steve,
I have imported securitycenter and did pip install too, but while calling securitycenter.SecurityCenter('ADDRESS','username','password') I am getting the error:
    sc = securitycenter.SecurityCenter(server,username,password)
AttributeError: 'module' object has no attribute 'SecurityCenter'

further from securitycenter import SecurityCenter4 gives error : 
ImportError: cannot import name SecurityCenter4

Can you please help me figure out what is going wrong.

**Comment by Electronickss** [comment]
make sure that you specify at the top of your script

`from securitycenter import SecurityCenter4`

I had a similar error and only had

`import securitycenter`

at the top of my script. Instead switching it to the specific one I needed, fixed the problem.

**Comment by sidgupt** [comment]
Hey I made some progress but still stuck. instead of SecurityCenter4 I am using sc4 in import and therefore the call now looks like 
sc = sc4.SecurityCenter4(server,username,password) where server = 'https://ip_address'

But still I am getting error:

    sc = sc4.SecurityCenter4(server,username,password)
  File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 38, in __init__
    self.system = self._system()
  File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 697, in _system
    return self.raw_query('system', 'init')
  File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 119, in raw_query
    data = self.post('', **kwargs)
  File "/Library/Python/2.7/site-packages/securitycenter/base.py", line 87, in post
    resp = self._session.post(self._url(path), **self._builder(**kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //***.***.***.***:username/request.php (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10829e4d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

Can you please help me figure out what is going wrong.

**Comment by sidgupt** [comment]
Hey I made some progress but still stuck. instead of SecurityCenter4 I am
using sc4 in import and therefore the call now looks like
sc = sc4.SecurityCenter4(server,username,password) where server = '
https://ip_address'

But still I am getting error:

sc = sc4.SecurityCenter4(server,username,password)

File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 38, in
init
self.system = self._system()
File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 697,
in _system
return self.raw_query('system', 'init')
File "/Library/Python/2.7/site-packages/securitycenter/sc4.py", line 119,
in raw_query
data = self.post('', kwargs)
File "/Library/Python/2.7/site-packages/securitycenter/base.py", line 87,
in post
resp = self._session.post(self._url(path), **self._builder(kwargs))
File "/Library/Python/2.7/site-packages/requests/sessions.py", line 518, in
post
return self.request('POST', url, data=data, json=json, kwargs)
File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in
request
resp = self.send(prep, *

*send_kwargs)File "/Library/Python/2.7/site-packages/requests/sessions.py",
line 585, in sendr = adapter.send(request, **kwargs)
File "/Library/Python/2.7/site-packages/requests/adapters.py", line 467, in
send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https',
port=443): Max retries exceeded with url: //*.*.*.***:username/request.php
(Caused by NewConnectionError(': Failed to establish a new connection:
[Errno 8] nodename nor servname provided, or not known',))

Can you please help me figure out what is going wrong.

Thanks,
Siddharth

**Comment by Electronickss** [comment]
This is from the examples folder. I noticed your code looks a little different so I think you might just have a formatting issue.

Try:

```
from securitycenter import SecurityCenter4

username = 'uname'
password = 'passwd'
host = 'fullyqualified.domain.name'

sc = SecurityCenter4(host)
sc.login(username,password)
```

Taking that a bit farther, I am reading in my credentials from a file with the permissions set to read only from that user. 

```
from securitycenter import SecurityCenterX

sc = SecurityCenterX('fullyqualified.domain.name')
with open('/Users/<user>/security_center_automation/scManager.txt') as f:
    credentials=f.readlines()
    user = (credentials[0]).rstrip()
    passwd = (credentials[1]).rstrip()
    sc.login(user, passwd)
```

I hope that helps

**Comment by sidgupt** [comment]
Thanks Nick. That helped, I was using full webpage name instead of host, just using ip solved the issue.

**Comment by Electronickss** [comment]
Glad to hear that
