### ISSUE TITLE
downloader.py

### ISSUE THREAD

**Issue by MalwareViz** [SteveMcGrath/pySecurityCenter#46]
#This did not work for me.
#I believe the fix should be:
#%s should be %d

resp = sc.get('scanResult', params={
        'startTime': findate.strftime('%d'),
        'fields': 'name,finishTime,downloadAvailable,repository',
})

**Comment by SteveMcGrath** [comment]
unfortunately strftime is using values set by the format described below:

https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

I did update the downloader script to convert using time.mktime instead.  This should be the more correct way to handle this anyhow.

Thanks for the patience, life's been super-busy as of late.

**Comment by MalwareViz** [comment]
Thank you for getting this taken care of.
Much appreciated.
