### ISSUE TITLE
report_downloader.py args issue

### ISSUE THREAD

**Issue by middleagedman** [SteveMcGrath/pySecurityCenter#49]
I think this never passes additional arguments from the Reports section to the def download function.. I.e. specifying "Name" doesn't filter out reports properly.

    download(sc,
        age=config.getint('Reports', 'age'),
        path=config.get('Reports', 'path')
    )

Then the def has

`def download(sc, age=0, path='reports', name='name', **args):`

And args is never populated with lists, so the "name" check following it doesn't ever match

            if 'name' in args and args['name'] not in report['name']:
                continue

Looks like the fix is just adding "name=config.get('Reports', 'name')" to the download call?  Maybe Reports, type too?

**Comment by SteveMcGrath** [comment]
keep in mind it was only an example, and not intended to be a completed solution.  If you'd like to extend the example, I'll happily accept a pull.
