### ISSUE TITLE
Data Cleanup

### ISSUE THREAD

**Issue by InfoSecured** [SteveMcGrath/pySecurityCenter#50]
So, this is awesome, even for a python rookie.  My question is, do you have a way to clean up the data that is returning from using sc.analysis?  For instance, if I'm requesting all vulns from an IP address, I'm getting a ton of unnecessary data back with the good data such as MAC address, Protocol, netbios name, etc.  Is there a way to clean it up so that I see something like:

Plugin ID: 72704
Plugin Name: .Net Framework Unsupported
Severity: Critical

Plugin ID: 12104
Plugin Name: McAfee something
Severity: Critical

And so on..?

**Comment by SteveMcGrath** [comment]
Whats the call your making?

**Comment by InfoSecured** [comment]
Thanks for the super quick reply. I'm calling this for 1 IP:

details = sc.analysis(('ip', '=', ips), ('severity', '=', severity),
('repositoryIDs', '=', repository), tool='listvuln', sortDir='desc',
sortField='severity', soureType='cumulative')
print(details)

Jason Lazerus M.S., GPEN, GCIH, GCFE, GCED, GSEC
InfoSecured

On May 26, 2017, at 5:01 PM, Steven McGrath <notifications@github.com>
wrote:

Whats the call your making?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/SteveMcGrath/pySecurityCenter/issues/50#issuecomment-304387367>,
or mute the thread

**Comment by SteveMcGrath** [comment]
Sorry for the delay in this, however the response objects should have everything there already for ya.
