### ISSUE TITLE
sc.upload() not returning filename

### ISSUE THREAD

**Issue by WTFender** [SteveMcGrath/pySecurityCenter#54]
First of all, great tool! Thanks so much!

From the documentation:
"...sc.upload() function that accepts a file object. It will return with the relevant information (including things like the temporary filename you will need in the subsequent calls)."

When I use sc.upload() to upload a file, I get a 200 response, but no other details.

>>> from securitycenter import SecurityCenter5
>>> sc = SecurityCenter5('###')
>>> sc.login('###','###')
>>> sc.upload('/Users/test/test.txt')
<Response [200]>

I'm trying to import assets from these uploaded files, but I need the temporary upload name to reference.

Any Ideas?

**Comment by SteveMcGrath** [comment]
Try:
sc.post('file/upload', files={'Filedata': open(filename)}).json()['response']['filename']

**Comment by WTFender** [comment]
I'm sure I am just misusing this, but here is what I get now...

>>> from securitycenter import SecurityCenter5
>>> sc = SecurityCenter5('###')
>>> sc.login('###','###')
>>> sc.post('file/upload', files={'Filedata': open('/Users/mcinm054/test/test2.txt')}).json()['response']['filename']
u'4auBHJ'

When I pass u'4auBHJ' as a filename to /asset/import (with doubt lol), it isn't found:
"Unable to find the specified file upload for attribute 'filename'.\n"

**Comment by WTFender** [comment]
Hmm strange... So I intercepted the http response with a proxy and I am getting the filename passed back... it just doesn't seem to be working with /asset/import.

{
    "error_code": 0,
    "error_msg": "",
    "response": {
        "content": "",
        "context": "",
        "filename": "PS50Te",
        "originalFilename": "test2.xml"
    },
    "timestamp": 1508520381,
    "type": "regular",
    "warnings": []
}
