### ISSUE TITLE
API documentation changed on Tenable's site

### ISSUE THREAD

**Issue by zadzagy** [SteveMcGrath/pySecurityCenter#59]
Reading through the help module for securitycenter.sc5, it lists the following URL for Tenable's official API documenation:

https://support.tenable.com/support-center/cerberus-support-center/includes/widgets/sc_api/index.html

This site is down, and now api docs are located here:

https://docs.tenable.com/sccv/api/index.html

**Comment by SteveMcGrath** [comment]
Please refer to the work being done on pyTenable for any future efforts.
